from typing import Protocol

from .dto import QuizFilter
from .entities.author import Author, AuthorID
from .entities.quiz import Quiz, QuizID
from .entities.submission import Submission


class QuizRepository(Protocol):
    def get(self, quiz_id: str) -> "Quiz": ...
    def save(self, quiz: "Quiz") -> None: ...
    def list(self, filter_: QuizFilter) -> list["Quiz"]: ...


class SubmissionRepository(Protocol):
    def by_author(self, author_id: AuthorID) -> list["Submission"]: ...
    def by_quiz(
        self, quiz_id: QuizID, page: int | None = None, page_size: int | None = None
    ) -> list["Submission"]: ...
    def save(self, submission: "Submission") -> None: ...
    def get(self, submission_id: str) -> "Submission": ...


class AuthorRepository(Protocol):
    def by_email(self, email: str) -> "Author": ...
    def save(self, author: "Author") -> None: ...
